spring:
  datasource:
    url: jdbc:mariadb://localhost:3303/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

logging.level:
  root: info
  org.hibernate.SQL: debug
# org.hibernate.type: trace          #Spring boot 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #Spring boot 3.x, hibernate6

