server:
  port: 0

spring:
  application:
    name: image-service
  config:
    import: secret/application-secret.yml

  datasource:
    url: jdbc:mariadb://localhost:3303/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka.clouter.kr/eureka


logging.level:
  root: info
  org.hibernate.SQL: debug
# org.hibernate.type: trace          #Spring boot 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #Spring boot 3.x, hibernate6

