server:
  port: 5000

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mariadb://localhost:13306/test2
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.LongDeserializer
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: clout-consumer-group
      auto-offset-reset: earliest

message:
  topic:
    name: test-topic-name
