cloud:
  aws:
    credentials:
      accessKey: AKIA42XKLCL6XY7LDBJF
      secretKey: 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
    s3:
      bucket: yangkidsbucket
    region:
      static: ap-northeast-2
    stack:
      auto: false