cloud:
  aws:
    credentials:
      accessKey: AKIA42XKLCL6R2IKU44K
      secretKey: 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
    s3:
      bucket: yangkidsbucket
    region:
      static: ap-northeast-2
    stack:
      auto: false