server:
  port: 0

spring:
  application:
    name: advertisement-service
  datasource:
    url: jdbc:mariadb://3.38.213.43:3303/advertisementdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: clout
    password: zmffkdnxm409!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

#    open-in-view: false
springdoc:
  swagger-ui:
    path: /api/swagger-ui
    use-root-path: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka.clouter.kr/eureka