server:
  port: 8889

spring:
  application:
    name: advertisement-service
  datasource:
    url: jdbc:mariadb://localhost:3306/advertiserment
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

#    open-in-view: false
springdoc:
  swagger-ui:
    path: /api/swagger-ui
    use-root-path: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka