server:
  port: 8888

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: chat-service
  datasource:
    url: jdbc:mariadb://localhost:3306/chat
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  data:
    mongodb:
      uri: mongodb://test:1234@localhost:27017/test
  jpa:
    #    open-in-view: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

jwt:
  secret: VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=
  refresh-token-validity-in-seconds: 1209600 # 14?
  access-token-validity-in-seconds: 43200 # 12??

springdoc:
  swagger-ui:
    path: /swagger-ui
    use-root-path: true
