server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka.clouter.kr/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        # MEMBER-service routes
        # 인증 인가 api
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/members/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        # 광고주 api
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/advertisers/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
        # 클라우터 api
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/clouters/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
        # Image api
        - id: image-service
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image-service/images/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/image-service/(?<segment>.*), /$\{segment}
        #            - AuthorizationHeaderFilter
        # swagger 요청
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/swagger-ui
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        #    - AuthorizationHeaderFilter
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/swagger-ui/**
          filters:
            - RemoveRequestHeader=Cookie
        #    - AuthorizationHeaderFilter
        - id: advertisement-service
          uri: lb://ADVERTISEMENT-SERVICE
          predicates:
            - Path=/advertisement-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/advertisement-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: contract-service
          uri: lb://CONTRACT-SERVICE
          predicates:
            - Path=/contract-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/contract-service/(?<segment>.*), /$\{segment}
#        - id: MEMBER-service
#          uri: lb://MEMBER-SERVICE
#          predicates:
#            - Path=/MEMBER-service/v3/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/MEMBER-service/(?<segment>.*), /$\{segment}
#        #    - AuthorizationHeaderFilter

#        - id: MEMBER-service
#          uri: lb://MEMBER-SERVICE
#          predicates:
#            - Path=/v3/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/MEMBER-service/(?<segment>.*), /$\{segment}
#          #    - AuthorizationHeaderFilter

jwt:
  secret: VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=