server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        # user-service routes
        # 인증 인가 api
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/members/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        # 광고주 api
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/advertisers/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
        # 클라우터 api
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/clouters/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
        # swagger 요청
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/swagger-ui
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #    - AuthorizationHeaderFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/swagger-ui/**
          filters:
            - RemoveRequestHeader=Cookie
        #    - AuthorizationHeaderFilter
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/v3/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#        #    - AuthorizationHeaderFilter

#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/v3/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#          #    - AuthorizationHeaderFilter

jwt:
  secret: VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=